import Head from "next/head";
import styles from "../styles/auth.module.css";
import "firebase/database";
import LoadingPage from "@/pages/components/LoadingPage";
import Sidebar from "@/pages/Chat";
import { useSession, signIn, signOut } from "next-auth/react";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "@/firebase";

export default function Home() {
  const { data: session } = useSession();
  const [user, loading] = useAuthState(auth);
  if (!loading) {
    // signOut()
    return (
      <>
        <Head>
          <title>Chat app</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/post.png" />
        </Head>
        {loading ? <LoadingPage/> : !session ? (
          <AuthPage />
        ) : (
          <div className={styles.homePage}>
            <div className={styles.container}>
              <Sidebar load={loading} />            
            </div>
          </div>
        )}
      </>
    );
  }
}

function AuthPage() {
  return (
    <div className={styles.authPage}>
      <div className={styles.form}>
        <button onClick={() => signIn({ callbackUrl: "/" })}>
          Sign in with Google
        </button>
      </div>
    </div>
  );
}
